Repository pytorch/pytorch.github.io, pull requests merged in 2022-04, with the labels that each got.

#977 Update stable and nightly wheel links to ROCm4.5.2
  _includes/quick-start-module.js
  _includes/quick_start_local.html
  assets/quick-start-module.js
  published_versions.json
Labels: cla signed, module: rocm

#1001 Fix link to torchvision in mobile menu
  _includes/mobile_menu.html
Labels: cla signed

#1002 Fix an error in the site build
  .circleci/config.yml
Labels: cla signed

#942 Create avalanche
  _ecosystem/avalanche
Labels: cla signed

#1005 Update Gemfile and ruby version
  .ruby-version
  Gemfile
Labels: dependencies, cla signed
